name: Greetings

on: [pull_request, issues]

jobs:
  greeting: Hello!
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'F'' first issue'
        pr-message: 'F?' first pr'
